// The per-project preview app: a Next.js + Tailwind + shadcn project at
// <project>/.prism/preview/ that Claude Code composes mockups into and the
// face server serves as a static export under /api/<slug>/preview/. This
// module writes the scaffold once (never over an existing one — that would
// clobber whatever shadcn/MagicUI components have been installed since),
// keeps the four token-derived files in step with design.md, and owns the
// mockup manifest the index page and EVE's status tool read.
//
// Every generated file carries a "generated — edit design.md instead" note so
// a human who opens the folder does not fix the wrong layer.
import fs from "node:fs";
import path from "node:path";
import { audit } from "../core/audit.js";
import { writeFileAtomic } from "../core/atomic.js";
import { renderCatalogMarkdown } from "./catalog.js";
import { ensureProjectLayout } from "./docs.js";
import { assertSlug, assertWithinProject } from "./paths.js";
import { renderComponentsJson, renderFontsTs, renderGlobalsCss, renderTailwindConfig, spliceGlobalsCss } from "./tokens.js";
import { previewBasePath } from "./types.js";
import type { DesignTokens, ProjectRef } from "./types.js";

// Relative to the preview dir. package.json is deliberately last: it is the
// "scaffold exists" marker, so writing it after everything else means a crash
// mid-scaffold leaves a dir the next call finishes rather than skips.
export const SCAFFOLD_FILES: readonly string[] = [
  "next.config.mjs",
  "tsconfig.json",
  "postcss.config.mjs",
  "tailwind.config.ts",
  "components.json",
  "next-env.d.ts",
  ".gitignore",
  "lib/utils.ts",
  "lib/fonts.ts",
  "app/layout.tsx",
  "app/globals.css",
  "app/page.tsx",
  "prism/component_catalog.md",
  "prism/mockups.json",
  "public/assets/.gitkeep",
  "README.md",
  "package.json",
];

// The files that are pure functions of design.md's tokens block. A token
// change re-renders exactly these; everything else in the scaffold is
// written once and thereafter belongs to whoever composes in the app.
// Only the files that carry token VALUES are refreshed on a design.md edit.
// tailwind.config.ts and components.json reference CSS variables / settings
// and are patched by the shadcn CLI (keyframes, animations) after scaffold —
// re-rendering them would silently undo those patches.
const TOKEN_FILES: readonly string[] = ["app/globals.css", "lib/fonts.ts"];

const MANIFEST_REL = path.join("prism", "mockups.json");
const DEFAULT_NEXT_VERSION = "^15.3.0";

export function previewDir(ref: ProjectRef): string {
  return path.join(ref.root, ".prism", "preview");
}

// ── manifest types ──────────────────────────────────────────────────────────

export interface MockupEntry {
  feature: string;
  screen: string;
  title: string;
  url: string;
  builtAt: string;
}

export interface MockupManifest {
  project: string;
  mockups: MockupEntry[];
}

// ── renderers (pure) ────────────────────────────────────────────────────────

function renderPackageJson(slug: string, nextVersion: string): string {
  const pkg = {
    name: `${slug}-preview`,
    private: true,
    scripts: { dev: "next dev", build: "next build", lint: "next lint" },
    dependencies: {
      next: nextVersion,
      react: "^19.0.0",
      "react-dom": "^19.0.0",
      "tailwindcss-animate": "^1.0.7",
      "class-variance-authority": "^0.7.1",
      clsx: "^2.1.1",
      "tailwind-merge": "^3.0.2",
      "lucide-react": "^0.475.0",
      motion: "^12.0.0",
    },
    devDependencies: {
      typescript: "^5.7.0",
      "@types/node": "^22",
      "@types/react": "^19",
      "@types/react-dom": "^19",
      tailwindcss: "^3.4.17",
      postcss: "^8.5",
      autoprefixer: "^10.4",
    },
  };
  return JSON.stringify(pkg, null, 2) + "\n";
}

// Static export under the face server's basePath. typescript.ignoreBuildErrors
// stays false on purpose: a mockup that does not type-check is a mockup that
// did not build, and the composer must hear that rather than ship a blank page.
function renderNextConfig(basePath: string): string {
  return `// Generated by EVE's design agent — edit design.md, not this file.
/** @type {import('next').NextConfig} */
const nextConfig = {
  output: "export",
  trailingSlash: true,
  basePath: ${JSON.stringify(basePath)},
  assetPrefix: ${JSON.stringify(basePath)},
  images: { unoptimized: true },
  reactStrictMode: true,
  eslint: { ignoreDuringBuilds: true },
  typescript: { ignoreBuildErrors: false },
};

export default nextConfig;
`;
}

function renderTsconfig(): string {
  const json = {
    compilerOptions: {
      target: "ES2017",
      lib: ["dom", "dom.iterable", "esnext"],
      allowJs: true,
      skipLibCheck: true,
      strict: true,
      noEmit: true,
      esModuleInterop: true,
      module: "esnext",
      moduleResolution: "bundler",
      resolveJsonModule: true,
      isolatedModules: true,
      jsx: "preserve",
      incremental: true,
      plugins: [{ name: "next" }],
      paths: { "@/*": ["./*"] },
    },
    include: ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts"],
    exclude: ["node_modules", "out"],
  };
  return JSON.stringify(json, null, 2) + "\n";
}

function renderPostcssConfig(): string {
  return `// Generated by EVE's design agent.
/** @type {import('postcss-load-config').Config} */
const config = {
  plugins: {
    tailwindcss: {},
    autoprefixer: {},
  },
};

export default config;
`;
}

function renderNextEnv(): string {
  return `/// <reference types="next" />
/// <reference types="next/image-types/global" />
`;
}

function renderGitignore(): string {
  return `node_modules/
.next/
out/
*.tsbuildinfo
`;
}

function renderUtilsTs(): string {
  return `import { clsx, type ClassValue } from "clsx";
import { twMerge } from "tailwind-merge";

// The shadcn convention: merge conditional classes and let Tailwind's later
// utility win, so a component's variant can be overridden by a caller's className.
export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs));
}
`;
}

// The root layout is written once at scaffold time (the mode class is baked
// in); a later mode flip in design.md still restyles everything through
// globals.css, which puts the palette on :root as well as .dark.
function renderLayoutTsx(slug: string, tokens: DesignTokens): string {
  const darkClass = tokens.mode === "dark" ? '"dark"' : '""';
  return `import type { Metadata } from "next";
import type { ReactNode } from "react";
import "./globals.css";
import { fontVars } from "@/lib/fonts";
import { cn } from "@/lib/utils";

// Generated by EVE's design agent — the palette and fonts come from design.md.
export const metadata: Metadata = {
  title: ${JSON.stringify(`${slug} — design previews`)},
  description: ${JSON.stringify(`Static design previews for ${slug}, composed from design.md.`)},
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en" className={cn(fontVars, ${darkClass})} suppressHydrationWarning>
      <body className="min-h-dvh bg-background text-foreground font-body antialiased">{children}</body>
    </html>
  );
}
`;
}

// The index: an editorial list of everything built so far. Hrefs are
// basePath-relative because <Link> prepends next.config's basePath itself;
// writing the full /api/<slug>/preview/… here would double it.
function renderIndexPageTsx(slug: string): string {
  return `import Link from "next/link";
import rawManifest from "../prism/mockups.json";

// Generated by EVE's design agent — the manifest is kept by the agent after
// each successful build; this page just reads it at build time.
interface Mockup {
  feature: string;
  screen: string;
  title: string;
  url: string;
  builtAt: string;
}
interface Manifest {
  project: string;
  mockups: Mockup[];
}
const manifest: Manifest = rawManifest;

export default function IndexPage() {
  const mockups = [...manifest.mockups].sort((a, b) =>
    a.feature === b.feature ? a.screen.localeCompare(b.screen) : a.feature.localeCompare(b.feature),
  );
  return (
    <main className="mx-auto flex min-h-dvh w-full max-w-3xl flex-col gap-10 px-6 py-16">
      <header className="flex flex-col gap-3">
        <p className="font-mono text-xs uppercase tracking-[0.08em] text-muted-foreground">design previews</p>
        <h1 className="font-display text-5xl leading-none tracking-tight">${slug}</h1>
        <p className="max-w-prose text-muted-foreground">
          {mockups.length === 0
            ? "Nothing built yet. The first dispatched screen will appear here."
            : \`\${mockups.length} screen\${mockups.length === 1 ? "" : "s"} built from design.md.\`}
        </p>
      </header>
      {mockups.length > 0 && (
        <ul className="flex flex-col divide-y divide-border border-y border-border">
          {mockups.map((m) => (
            <li key={\`\${m.feature}/\${m.screen}\`}>
              <Link
                href={\`/\${m.feature}/\${m.screen}/\`}
                className="group flex items-baseline justify-between gap-6 py-4 transition-colors hover:text-primary"
              >
                <span className="flex flex-col gap-1">
                  <span className="text-lg">{m.title}</span>
                  <span className="font-mono text-xs text-muted-foreground">
                    {m.feature}/{m.screen}
                  </span>
                </span>
                <time dateTime={m.builtAt} className="font-mono text-xs text-muted-foreground">
                  {m.builtAt.slice(0, 10)}
                </time>
              </Link>
            </li>
          ))}
        </ul>
      )}
      <footer className="font-mono text-xs text-muted-foreground">
        generated — edit design.md, not this app
      </footer>
    </main>
  );
}
`;
}

function renderManifestJson(slug: string): string {
  const manifest: MockupManifest = { project: slug, mockups: [] };
  return JSON.stringify(manifest, null, 2) + "\n";
}

function renderReadme(slug: string, basePath: string): string {
  return `# ${slug} — preview app

Generated by EVE's design agent. This is the Next.js + Tailwind + shadcn app
that mockups for **${slug}** are composed into. It is not the product; it is
the sketchbook the product's screens get drawn in.

## How it is built

- \`npm install\` once (the agent does this on the first dispatch).
- Components are added with \`npx shadcn@latest add <name>\` (shadcn/ui) or
  \`npx shadcn@latest add "https://magicui.design/r/<name>.json"\` (MagicUI);
  see \`prism/component_catalog.md\` for the full catalog. Both land in
  \`components/ui/<name>.tsx\` (MagicUI items are \`registry:ui\`, so the
  shadcn CLI files them under the ui alias) and are imported from
  \`@/components/ui/<name>\`.
- Each mockup is a page at \`app/<feature>/<screen>/page.tsx\`.
- \`npm run build\` produces a static export in \`out/\` (\`output: "export"\`,
  trailing slashes on), which the face server serves at \`${basePath}/\`.
  A built screen lives at \`${basePath}/<feature>/<screen>/\`.
- \`prism/mockups.json\` is the manifest of built screens; the index page
  (\`app/page.tsx\`) renders it.
- Images the agent generates land in \`public/assets/<feature>/<slug>.png\`
  and are referenced by their full served URL.

## Generated — edit design.md instead

\`tailwind.config.ts\`, \`app/globals.css\`, \`lib/fonts.ts\` and
\`components.json\` are rendered from the tokens block in the project's
\`design.md\` and are overwritten whenever it changes. Change fonts, colours,
radius or mode there, not here.
`;
}

// Every scaffold file as relPath → content. Pure, so the whole app can be
// inspected in a test without touching disk.
export function renderScaffoldFiles(
  ref: ProjectRef,
  tokens: DesignTokens,
  opts?: { nextVersion?: string },
): Record<string, string> {
  const slug = assertSlug(ref.slug, "project slug");
  const basePath = previewBasePath(slug);
  const files: Record<string, string> = {
    "package.json": renderPackageJson(slug, opts?.nextVersion ?? DEFAULT_NEXT_VERSION),
    "next.config.mjs": renderNextConfig(basePath),
    "tsconfig.json": renderTsconfig(),
    "postcss.config.mjs": renderPostcssConfig(),
    "tailwind.config.ts": renderTailwindConfig(tokens),
    "components.json": renderComponentsJson(tokens, { basePath }),
    "next-env.d.ts": renderNextEnv(),
    ".gitignore": renderGitignore(),
    "lib/utils.ts": renderUtilsTs(),
    "lib/fonts.ts": renderFontsTs(tokens),
    "app/layout.tsx": renderLayoutTsx(slug, tokens),
    "app/globals.css": renderGlobalsCss(tokens),
    "app/page.tsx": renderIndexPageTsx(slug),
    "prism/component_catalog.md": renderCatalogMarkdown(),
    "prism/mockups.json": renderManifestJson(slug),
    "public/assets/.gitkeep": "",
    "README.md": renderReadme(slug, basePath),
  };
  return files;
}

// ── disk ────────────────────────────────────────────────────────────────────

function writeRel(dir: string, rel: string, text: string): string {
  const abs = assertWithinProject(dir, rel);
  fs.mkdirSync(path.dirname(abs), { recursive: true });
  writeFileAtomic(abs, text);
  return abs;
}

// Writes the whole preview app unless one is already there. The check is on
// package.json alone: once a scaffold exists it belongs to the composer (and
// to npm install, and to every shadcn add since), so nothing here may touch
// it again — token files go through refreshTokenFiles instead.
export function prepareScaffold(ref: ProjectRef, tokens: DesignTokens): { created: boolean; dir: string; files: string[] } {
  const dir = previewDir(ref);
  if (fs.existsSync(path.join(dir, "package.json"))) return { created: false, dir, files: [] };
  ensureProjectLayout(ref);
  fs.mkdirSync(dir, { recursive: true });
  const rendered = renderScaffoldFiles(ref, tokens);
  const files: string[] = [];
  for (const rel of SCAFFOLD_FILES) {
    const text = rendered[rel];
    if (text === undefined) throw new Error(`scaffold: no renderer for ${rel} — SCAFFOLD_FILES and renderScaffoldFiles disagree`);
    files.push(writeRel(dir, rel, text));
  }
  audit("design_scaffold_created", { project: ref.slug, dir, files: files.length });
  return { created: true, dir, files };
}

// Re-renders only the token-derived files, writing each one whose content
// differs from what is on disk (a missing file counts as different). Returns
// the absolute paths written, so a caller can say "nothing changed" honestly.
export function refreshTokenFiles(ref: ProjectRef, tokens: DesignTokens): string[] {
  const dir = previewDir(ref);
  const rendered = renderScaffoldFiles(ref, tokens);
  const written: string[] = [];
  for (const rel of TOKEN_FILES) {
    const text = rendered[rel]!;
    const abs = assertWithinProject(dir, rel);
    let current: string | null = null;
    try {
      current = fs.readFileSync(abs, "utf8");
    } catch {
      current = null;
    }
    if (current === text) continue;
    // globals.css: splice the fenced token region so CLI-appended keyframes
    // below the end marker survive; a file without a fence is overwritten.
    const next = rel === "app/globals.css" && current !== null ? (spliceGlobalsCss(current, text) ?? text) : text;
    if (next === current) continue;
    written.push(writeRel(dir, rel, next));
  }
  if (written.length) audit("design_tokens_refreshed", { project: ref.slug, files: written });
  return written;
}

// ── mockup manifest ─────────────────────────────────────────────────────────

function isEntry(v: unknown): v is MockupEntry {
  if (typeof v !== "object" || v === null) return false;
  const o = v as Record<string, unknown>;
  return ["feature", "screen", "title", "url", "builtAt"].every((k) => typeof o[k] === "string");
}

function compareEntries(a: MockupEntry, b: MockupEntry): number {
  return a.feature === b.feature ? a.screen.localeCompare(b.screen) : a.feature.localeCompare(b.feature);
}

// A missing manifest is an empty one (a project that has never built); a
// corrupt one is an error worth hearing about, since the index page is built
// from it and a bad file would fail the next build anyway.
export function readMockupManifest(ref: ProjectRef): MockupManifest {
  const abs = assertWithinProject(previewDir(ref), MANIFEST_REL);
  let text: string;
  try {
    text = fs.readFileSync(abs, "utf8");
  } catch (err) {
    if ((err as NodeJS.ErrnoException).code === "ENOENT") return { project: ref.slug, mockups: [] };
    throw err;
  }
  let raw: unknown;
  try {
    raw = JSON.parse(text);
  } catch {
    throw new Error(`the mockup manifest at ${abs} is not valid JSON — fix or delete it and re-dispatch`);
  }
  const o = (typeof raw === "object" && raw !== null ? raw : {}) as Record<string, unknown>;
  const list = Array.isArray(o.mockups) ? o.mockups : [];
  const bad = list.filter((e) => !isEntry(e)).length;
  if (bad) throw new Error(`the mockup manifest at ${abs} has ${bad} malformed entr${bad === 1 ? "y" : "ies"} (each needs feature, screen, title, url, builtAt)`);
  return {
    project: typeof o.project === "string" ? o.project : ref.slug,
    mockups: (list as MockupEntry[]).slice().sort(compareEntries),
  };
}

// Replaces the entry for the same feature+screen (a rebuild) or adds a new
// one; the file stays sorted so diffs and the index page are stable.
export function upsertMockup(ref: ProjectRef, entry: MockupEntry): void {
  assertSlug(entry.feature, "feature slug");
  assertSlug(entry.screen, "screen name");
  const manifest = readMockupManifest(ref);
  const rest = manifest.mockups.filter((m) => !(m.feature === entry.feature && m.screen === entry.screen));
  const next: MockupManifest = { project: manifest.project, mockups: [...rest, { ...entry }].sort(compareEntries) };
  writeRel(previewDir(ref), MANIFEST_REL, JSON.stringify(next, null, 2) + "\n");
  audit("design_mockup_upserted", { project: ref.slug, feature: entry.feature, screen: entry.screen, url: entry.url });
}

// ── state probes ────────────────────────────────────────────────────────────

export function isInstalled(ref: ProjectRef): boolean {
  return fs.existsSync(path.join(previewDir(ref), "node_modules", "next"));
}

export function isBuilt(ref: ProjectRef, feature: string, screen: string): boolean {
  const rel = path.join("out", assertSlug(feature, "feature slug"), assertSlug(screen, "screen name"), "index.html");
  return fs.existsSync(assertWithinProject(previewDir(ref), rel));
}

export function pageFile(ref: ProjectRef, feature: string, screen: string): string {
  const rel = path.join("app", assertSlug(feature, "feature slug"), assertSlug(screen, "screen name"), "page.tsx");
  return assertWithinProject(previewDir(ref), rel);
}
